### ISSUE TITLE
503 Service Unavailable - Application Error?

### ISSUE THREAD

**Issue by adithyaphilip** [TeamSwagmunchkins/pescom-server#3]
![image](https://cloud.githubusercontent.com/assets/5712241/13912805/e0487e20-ef66-11e5-949f-816a792d2872.png)
Any idea why this is happening? Bad hosting by heroku?

**Comment by ambuakshay** [comment]
wait for 10 minutes if you get a 503 Error.. It means that the heroku app has crashed.
It will restart in 10 minutes.. thats Heroku policy apparently
